VIRTS-3327
center-for-threat-informed-defense/caldera_pathfinder pull request #41
Opened 2021-12-12 23:50 UTC by CDJellen

Pathfinder host object extension.

New concepts for host/ability pairs including:
* freebie ability for a given host,
* freebie node (host which already has an implant deployed),
* `DENIED` ability for a given host,
* `DENIED` node (host which cannot be accessed),
* Ability success probabilities for each host

2021-12-15 00:45 UTC, elegantmoose requested changes

2021-12-15 00:45 UTC, elegantmoose commented on app/objects/secondclass/c_host.py
> +class HostAccess(Enum):
Make the enum values uppercase --> DENY, STANDARD etc..

2021-12-15 00:45 UTC, elegantmoose commented on app/objects/secondclass/c_host.py
> +        self.access = access or 0
Change to 0 to HostAccess.STANDARD

2021-12-15 00:45 UTC, elegantmoose commented on app/objects/secondclass/c_host.py
> +    access_prob = ma.fields.Dict(keys=ma.fields.String(), values=ma.fields.Float())
Is access_prob equivalent to 'ability probabilities' ?

2021-12-15 00:45 UTC, elegantmoose commented on app/objects/secondclass/c_host.py
> +    freebie_abilities = ma.fields.Dict(keys=ma.fields.String(), values=ma.fields.List())
Whats the sub-list for here?

2021-12-15 00:45 UTC, elegantmoose commented on app/objects/secondclass/c_host.py
> +    access_prob = ma.fields.Dict(keys=ma.fields.String(), values=ma.fields.Float())
And where is the overall host probability? (i.e. umbrella success probability for all abilities on a host)

2021-12-16 16:45 UTC, CDJellen commented on app/objects/secondclass/c_host.py
> +    access_prob = ma.fields.Dict(keys=ma.fields.String(), values=ma.fields.Float())
I'll try to explain my thoughts here, but if you have a different vision I'm happy to have further discussion on ways to implement this.  In the above, `access_prob` is slightly more abstract than just 'ability probabilities'.  Keys in `access_prob` could be an `adversary` or `ability`, with the associated probability of success.  The overall host probability is then the `max()` of the `dict` values.  

To present a motivating use case, we can assume three hosts, 1  has an implant, 2 and 3 which we would like to access.  On host 2,  that we can execute ability `A` with success `.3`.  On host 3, we have an entry `freebie_abilities` which aggregates credentials for credential dumping for all hosts that host 3 has connected to.  We assume we can exploit this with success `1.0`.  By choosing this path, we can now add a new entry in `access_prob` for host 2 for ability `B`, which may represent credential dumping using information gathered by host 3.  Host 2 now has `access_prob` entries for ability `A` with `0.3` and `B` with `0.9`, our overall probability is the `max` of `0.9` if we take the path of host 1 -> host 3 -> host 2.  However, if we wanted to go directly from host 1 to host 2, without exploiting host 3, our overall probability is `0.3`.  

The structure of `ability` or `adversary` key and success value seems sufficient for this purpose, however, we could also nest this dict within an outer dict as below:
```
access_prob = {
    uuid_for_adversary_1: {
        uuid_for_ability_1: 0.9,
        uuid_for_ability_2: 0.9,
        ...
        uuid_for_ability_n: 1
    },
    ...
    uuid_for_adversary_n: {
        ...
    }
}
```

2021-12-16 16:56 UTC, CDJellen commented on app/objects/secondclass/c_host.py
> +    freebie_abilities = ma.fields.Dict(keys=ma.fields.String(), values=ma.fields.List())
In this case, the sub list enables a few possibilities such as storing `fact` representations or storing the new edges or attributes which result from exploiting the host.  Referencing the example above, exploiting a freebie ability may result in a new `ability` or `adversary` which can be used against a different host in the network.  As it is a freebie_ability, we do not need to store the success probability, just the new information we gain by exploiting the ability.  This is another case where a dictionary of dictionaries could be appropriate, the list structure was selected as the `value` in the nested dictionary may be non-standard, such as a tuple of (`Host.ip`, `Host.access`) to represent another host on the network becoming available after exploiting the freebie ability.

2021-12-16 17:50 UTC, elegantmoose commented on app/objects/secondclass/c_host.py
> +    freebie_abilities = ma.fields.Dict(keys=ma.fields.String(), values=ma.fields.List())
Ah lets isolate that. This is not the logic for path finding. I have an idea for how modular path finding logic will work, and when we get to that we may add more fields/data structure then.

2021-12-17 19:39 UTC, elegantmoose commented on app/objects/secondclass/c_host.py
> +    access_prob = ma.fields.Dict(keys=ma.fields.String(), values=ma.fields.Float())
@CDJellen 
So, for now, Im going to override this paradigm for the simple, explicit one we outlined in ticket. Reason being is Im going to tackle the path finding logic in a later ticket and in a certain manner, thus I want these changes free of the path logic.

But I want you to note this paradigm for future re-evaluation after we get some more of the refactor complete.

Also:
-  Im still not following on the adversary:ability nesting, or rather why adversary is listed in there. 
- I still want a field for overall host probability as I want the user to be able to input "Hey, for this node, just give all abilities that apply to its OS/application environment this probability of success." regardless of that overall prob value being tied to any underlying individual probabilities. (this might turn out not optimal in the end but for now this simplifies the dev approach I have in mind for path finding)

2021-12-21 21:32 UTC, CDJellen commented on app/objects/secondclass/c_host.py
> +    access_prob = ma.fields.Dict(keys=ma.fields.String(), values=ma.fields.Float())
With these comments in mind, I've changed `access_prob` to record a `float` probability of getting an implant on the host, and added a new field called `possible_abilities` which records a list of abilities that could work on a given host based on the OS/application environment, alongside their probability of success (`float`).  The new fields for the `Host` object are presented below:

```
    freebie_abilities = ma.fields.List(ma.fields.String())
    possible_abilities = ma.fields.Nested(AbilitySchema())
    denied_abilities = ma.fields.List(ma.fields.String())
    access = ma.fields.Integer()
    access_prob = ma.fields.Number()
```
We could use a dictionary rather than developing a the new `AbilitySchema` but this change could be more extensible, enabling the addition of new, ability-specific fields.  The `AbilitySchema` is presented below for reference:

```
class AbilitySchema(ma.Schema):
    uuid = ma.fields.String()
    success_prob = ma.fields.Number()
```

2021-12-23 14:49 UTC, elegantmoose approved these changes

2021-12-23 14:50 UTC, merged